In [3]:
# numpy arrays are fixed sized containers of items
# 1. they only store a single data type
# 2. they can be one dimensional or multi dimensional
# 3. while elements can be modified, an array size can not change

# let's work with a simple array now.
# to start we need to import numpy and we import it is np, which is a convention

import numpy as np

# now we take a simple list
sales = [0, 3, 4, 8, 99, 102, 789, 776, 89, 325, 616]

sales_array = np.array(sales)

print(sales_array)
sales_array

[  0   3   4   8  99 102 789 776  89 325 616]


array([  0,   3,   4,   8,  99, 102, 789, 776,  89, 325, 616])

In [ ]:
# numpy's array function converts python lists and tuples into numpy arrays.

# Properties of an Array:
# 1. ndim > number of dimensions in the array. We can have one dimension, similar to lists in python, 2, 3, 4, 5 and so on dimensions in an array. In this course, we focus on 1 and 2 dimensional arrays.
# 2. shape > the size of array for each dimension
# 3. size > the total number of elements in an array
# 4. dtype > the data type of elements in an array

# also, one point to be noted here is that since the data type and the size of array is always fixed, python can in advance know the memory one such array will use. Due to this, numpy arrays become super efficient when it comes to mathematical operations.

In [4]:
# earlier we had created an array -> sales_array, let us check its type

type(sales_array)

numpy.ndarray

In [6]:
# numpy arrays are a ndarray Python data type, which stands for n dimensional array. Now, let us have a look at the properties of this very array that we have created

print(f"ndim: {sales_array.ndim}")
print(f"size: {sales_array.size}")
print(f"shape: {sales_array.shape}")
print(f"dtype: {sales_array.dtype}")

ndim: 1
size: 11
shape: (11,)
dtype: int64


In [8]:
# so, we have 1 dimension, with 11 elements, and shape is showing size of each dimension, and since we have only one dimension, it is showing 11, and finally dtype is int64 -> int

# now lets create some more arrays

new_array = np.array(range(5))
new_array_2d = np.array([range(5), range(5)])

print(new_array)
print(new_array_2d)


new_array, new_array_2d

[0 1 2 3 4]
[[0 1 2 3 4]
 [0 1 2 3 4]]


(array([0, 1, 2, 3, 4]),
 array([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]))

In [11]:
# now, let us look at the properties of both these arrays

print(f"1dim array:\nsize -> {new_array.size}\nshape -> {new_array.shape}\ndimensions -> {new_array.ndim}\ndtype -> {new_array.dtype}")

print(f"\n2dim array:\nsize -> {new_array_2d.size}\nshape -> {new_array_2d.shape}\ndimensions -> {new_array_2d.ndim}\ndtype -> {new_array_2d.dtype}")

1dim array:
size -> 5
shape -> (5,)
dimensions -> 1
dtype -> int64

2dim array:
size -> 10
shape -> (2, 5)
dimensions -> 2
dtype -> int64


In [ ]:
# now we can see the difference in the array properties. The first one is of a one dimensional array, where we have a total of 5 elements, so size is 5, shape is (5, ) -> we shall cover more about this. dimension is 1 and dtype is int. 

# now, in the second case, size is 10, since we have two arrays of 5 each, two dimensions, now the important part is shape, here, we see the shape is 2, 5 -> now, we can think of it like this -> 2 or the first number is the count of rows and the second number is the count of columns, though it shows that we have 2 dimensions of 5 elements each and finally dtype is same int64.

In [13]:
# next up is an assignment here we need to convert a python list into a numpy array and find out its properties. 

python_list = [x for x in range(1, 11)]
print(python_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [14]:
python_to_np = np.array(python_list)
print(python_to_np)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
# following are the properties:
print(f"{python_to_np.dtype} -> shows data type") 
print(f"{python_to_np.size} -> shows size") 
print(f"{python_to_np.shape} -> shows shape") 
print(f"{python_to_np.ndim} -> shows dimensions") 

int64 -> shows data type
10 -> shows size
(10,) -> shows shape
1 -> shows dimensions
